name: Daily Task Reminder

on:
  schedule:
    - cron: "*/2 * * * *"

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: List files (debug)
        run: ls -la

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"

      - name: Cache pip packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run task reminder
        env:
          SUPABASE_URL:    ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY:    ${{ secrets.SUPABASE_KEY }}
          RESEND_API_KEY:  ${{ secrets.RESEND_API_KEY }}
          SENDER_EMAIL:    ${{ secrets.SENDER_EMAIL }}
        run: python send_reminders.py